[package]
name = "shadertoy-browser"
version = "0.6.1"
description = "Small Shadertoy browser & viewer for Mac"
authors = ["Johan Andersson <repi@repi.se>"]
repository = "https://github.com/repi/shadertoy-browser"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["shaders", "shadertoy", "render", "mac", "metal"]
categories = ["rendering"]
exclude = ["screenshots/*"]
edition = "2018"

[badges]
travis-ci = { repository = "repi/shadertoy-browser" }
appveyor = { repository = "repi/shadertoy-browser" }

[workspace]
members = [
    "shadertoy"
]

[dependencies]
shadertoy = { path = "shadertoy", version = "0.6.1" }
floating-duration = "0.1.2"
chrono = "0.4.19"
rayon = "1.5.0"
clap = "2.33.3"
shaderc = "0.7.2"
serde = "1.0.125"
serde_json = "1.0.64"
winit = "0.24.0"
libc = "0.2.93"
foreign-types = "0.5.0"
rust-base58 = "0.0.4"
colored = "2.0.0"
reqwest = "0.11.2"
error-chain = "0.12.4"
open = "1.6.0"
indicatif = "0.15.0"
thread_profiler = "0.3.0"
log = "0.4.14"
fern = "0.6.0"
sha3 = "0.9.1"
gfx-backend-metal = { path = "../gfx/src/backend/metal", features = ["cross"] }
gfx-hal = { path = "../gfx/src/hal" }
gfx-auxil = { path = "../gfx/src/auxil/auxil" }

[profile.release]
debug = true

[features]
default = [ "profiler"]
profiler = ["thread_profiler/thread_profiler"]
